window:
  dimensions:
    columns: 120
    lines: 85
font:
  normal:
    family: "Fira Code"
    style: Light
  bold:
    family: "Fira Code"
    style: Medium
  italic:
    family: "Fira Code"
    style: "Light Italic"
