[font.bold]
family = "Fira Code"
style = "Medium"

[font.italic]
family = "Fira Code"
style = "Light Italic"

[font.normal]
family = "Fira Code"
style = "Light"

[window.dimensions]
columns = 120
lines = 85
