#!/usr/bin/env bash

cd ~/.dotfiles 

# Load the submodules
git submodule init
git submodule update

# Symlink the configs
ln -s ~/.dotfiles/.alacritty.toml  ~/.alacritty.toml
ln -s ~/.dotfiles/.config/nvim     ~/.config/nvim
ln -s ~/.dotfiles/.tmux.conf       ~/.tmux.conf
ln -s ~/.dotfiles/.xbindkeysrc     ~/.xbindkeysrc
ln -s ~/.dotfiles/.xprofile        ~/.xprofile
ln -s ~/.dotfiles/.zsh             ~/.zsh
ln -s ~/.dotfiles/.zshenv          ~/.zshenv
ln -s ~/.dotfiles/.zshrc           ~/.zshrc
ln -s ~/.dotfiles/.zsh_plugins.txt ~/.zsh_plugins.txt
